# Generated by Django 4.2.7 on 2024-02-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_of_post',
            field=models.TextField(max_length=2000),
        ),
    ]
