# Generated by Django 4.2.7 on 2024-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_text_of_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(choices=[('DA', 'Ежедневные глобальные новости'), ('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('ME', 'Медицина')], default='DA', help_text='category name', max_length=2, unique=True),
        ),
    ]
