# Generated by Django 4.2.7 on 2024-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_name_of_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(choices=[('DA', 'Ежедневные глобальные новости'), ('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('ME', 'Медицина')], default='DA', help_text='имя категории', max_length=2, unique=True),
        ),
    ]
