# Generated by Django 4.2.7 on 2024-04-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name_of_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_en',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_of_post_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_of_post_ru',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post_en',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='NE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post_ru',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='NE', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [ru]',
                'verbose_name_plural': 'post categorys [ru]',
                'db_table': 'news_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [en]',
                'verbose_name_plural': 'post categorys [en]',
                'db_table': 'news_postcategory_en',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
