openapi: 3.0.1
info:
    title: Новостной портал OpenAPI спецификация
    version: '0.0.1'
servers:
    - url: http://127.0.0.1:8000/
paths:
    /api/posts:
        get:
            summary: Method of getting post
            tags:
                - Posts
            operationId: getAllPosts
            responses:
                '200':
                    description: Successfully answer with list of posts
                    content:
                        application/json:
                            schema:
                              $ref: "#/components/schemas/Posts"

        post:
            summary: Method of creating post
            tags:
                - Posts
            operationId: createPost
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Post"
            responses:
                '200':
                    description: Successfully answer with post
                    content:
                        application/json:
                            schema:
                              $ref: "#/components/schemas/Post"

    /api/posts/{post_id}:
        get:
            summary: Method of getting post by id
            tags:
                - Posts
            operationId: getPostById
            parameters:
            - name: post_id
              in: path
              required: true
              description: ID of post
              schema:
                  type: string
            responses:
                '200':
                    description: Successfully answer with post
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Post"

        delete:
            summary: Method of deleting post by id
            tags:
                - Posts
            operationId: deletePostById
            parameters:
            - name: post_id
              in: path
              required: true
              description: ID of post
              schema:
                  type: integer
            responses:
                '204':
                    description: Successfully answer with deleting of post
                    content:
                        application/json: {}


components:
    schemas:
        Post:
            type: object
            description: Post
            required:
                - type_of_post
                - heading
                - text_of_post
                - author
                - category
            properties:
                id:
                    type: integer
                    readOnly: true
                    example: 1
                time_in:
                    type: string
                    description: Time of creating post
                    format: date-time
                    example: "2023-11-30T20:36:23.651000+01:00"
                type_of_post:
                    type: string
                    enum:
                        - NE - news
                        - AR - article
                    example: NE
                heading:
                    type: string
                    description: Heading
                    example: Белые медведи - белые!
                text_of_post:
                    type: string
                    description: Text of post
                    example: Мишки мишки мишки - они не шишки.
                author:
                    description: Author of post
                    items:
                        $ref: '#/components/schemas/Author'
                    example: "http://127.0.0.1:8000/api/authors/2/"
                rating:
                    type: integer
                    description: Rating of post
                    example: 5.0
                category:
                    type: array
                    description: Categories of post
                    items:
                        $ref: '#/components/schemas/Category'
                    example: "http://127.0.0.1:8000/api/categories/2/"
        Posts:
            type: array
            description: List of posts
            items:
                $ref: "#/components/schemas/Post"
        Category:
            type: object
            description: Category of Post
            required:
                - url_to_author
            properties:
                url_to_author:
                    type: string
                    description: URL to category
        Author:
            type: object
            description: Author of post
            required:
                - url_to_author
            properties:
                url_to_author:
                    type: string
                    description: URL to author
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                message:
                    type: string
                    description: Message about error
